//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResearchGate.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Artical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artical()
        {
            this.Comments = new HashSet<Comment>();
            this.Authors = new HashSet<Author>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public string Paper { get; set; }
        public string @abstract { get; set; }
        public HttpPostedFileBase pdfFile { get; set; }
        public string collaboratorsText { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
    }
}
